version: '3.8'

services:
  chromadb:
    build:
      context: .
    container_name: chromadb-ragbot
    ports:
      - 8800:8000
    env_file:
      - ./chromadb.env
    volumes:
      - ./chroma_db:/chroma/my_db
    restart: unless-stopped
