version: '3.8'

services:
  vectordb:
    build: 
      context: .
    container_name: chromadb-chatbot
    ports:
      - 8800:8000
    env_file:
      - ./chromadb.env
    volumes:
      - ./my_db:/chroma/my_db
    restart: unless-stopped